### PR TITLE
Actually serve tiles

### PR DESCRIPTION
**Pull request by migurski**
Follow-up to #3 that serves unified GeoJSON tiles and introduces test coverage.

### CODE REVIEW

**Comment by migurski** [comment]
I added Travis CI configuration and [verified that it works with a fork](https://travis-ci.org/migurski/sharedstreets-python/builds/351176277). I believe an admin needs to enable Travis for this repo at https://travis-ci.org/profile/sharedstreets.

**Comment by migurski** [comment]
Ping on this: @DenisCarriere or @kpwebb, any objection to adding Travis integration for tests?

**Comment by kpwebb** [comment]
@migurski No objection! sorry for letting this slip through (adding you as an admin...)

**Comment by migurski** [comment]
Thanks! Should I be seeing an invite here?

**Comment by kpwebb** [comment]
@migurski just re-tried, let me know if it worked this time.

**Comment by migurski** [comment]
That worked, thank you. Tests are running: https://travis-ci.org/sharedstreets/sharedstreets-python

**Pull request merged**
